export const GET_PROJECTS="GET_PROJECTS";
export const GET_PROJECT="GET_PROJECT";
export const SET_PROJECT="SET_PROJECT";
export const DEL_PROJECT="DEL_PROJECT";
export const PUT_PROJECT="PUT_PROJECT";
